version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3030:3030
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}